# fly.toml app configuration file generated for 1augustquizz on 2023-08-01T08:42:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "1augustquizz"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
